server:
  port: 9001
spring:
  application:
    name: superMonkeyTakeOut
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/super_monkey?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
    password: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间，30分钟

# MyBatis-Plus的相关配置
mybatis-plus:
  configuration:
    # 在映射实体或属性时，将数据库中表名和字段名中的下划线去掉，开启按照驼峰命名规则映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
# swagger
swagger:
  enable: true
# 图片上传路径
superMonkey:
  path: D:\My Development\My Project\StudyWork\super-orangutan-takeout\super-monkey-parent\src\main\resources\project-diagram\
